// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDY4Ns-6abDZ0y3eynY6Pv8yr_IhjlWmlg',
    appId: '1:1030223056150:web:05050ab35238607ef8d437',
    messagingSenderId: '1030223056150',
    projectId: 'labs2-4e375',
    authDomain: 'labs2-4e375.firebaseapp.com',
    storageBucket: 'labs2-4e375.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBIRNyip9Lh3w5HJp22QJwX2Qo7jjDUagY',
    appId: '1:1030223056150:android:408d185582b588a4f8d437',
    messagingSenderId: '1030223056150',
    projectId: 'labs2-4e375',
    storageBucket: 'labs2-4e375.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAtLB22cDmQWCFFbPmyS2zJ_Vy4OAuXt2Q',
    appId: '1:1030223056150:ios:da6f9faf7fb0d6aef8d437',
    messagingSenderId: '1030223056150',
    projectId: 'labs2-4e375',
    storageBucket: 'labs2-4e375.firebasestorage.app',
    iosBundleId: 'com.example.labs2',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAtLB22cDmQWCFFbPmyS2zJ_Vy4OAuXt2Q',
    appId: '1:1030223056150:ios:da6f9faf7fb0d6aef8d437',
    messagingSenderId: '1030223056150',
    projectId: 'labs2-4e375',
    storageBucket: 'labs2-4e375.firebasestorage.app',
    iosBundleId: 'com.example.labs2',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDY4Ns-6abDZ0y3eynY6Pv8yr_IhjlWmlg',
    appId: '1:1030223056150:web:4bc8c559c1768c88f8d437',
    messagingSenderId: '1030223056150',
    projectId: 'labs2-4e375',
    authDomain: 'labs2-4e375.firebaseapp.com',
    storageBucket: 'labs2-4e375.firebasestorage.app',
  );

}